### ISSUE TITLE
Error in installing the trimmed match package

### ISSUE THREAD

**Issue by wanyi11** [google/trimmed_match#1]
I was following along the installation guide and then got an error when installing the extension using the supplied setup.py file and setuptools and pip by calling the command line "python3 -m pip install ./trimmed_match" in the terminal.

Please see below for the stacktrace of error:

> (base) user:~ username$ python3 -m pip install ./trimmed_match
> 
> Processing ./trimmed_match
> 
> Requirement already satisfied: absl-py in ./opt/anaconda3/lib/python3.7/site-packages (from trimmed-match==1.0.0) (0.11.0)
> 
> Requirement already satisfied: numpy>=1.8.0rc1 in ./opt/anaconda3/lib/python3.7/site-packages (from trimmed-match==1.0.0) (1.17.2)
> 
> Requirement already satisfied: pandas in ./opt/anaconda3/lib/python3.7/site-packages (from trimmed-match==1.0.0) (0.25.1)
> 
> Requirement already satisfied: matplotlib in ./opt/anaconda3/lib/python3.7/site-packages (from trimmed-match==1.0.0) (3.3.0)
> 
> Requirement already satisfied: scipy in ./opt/anaconda3/lib/python3.7/site-packages (from trimmed-match==1.0.0) (1.3.1)
> 
> Requirement already satisfied: seaborn in ./opt/anaconda3/lib/python3.7/site-packages (from trimmed-match==1.0.0) (0.9.0)
> 
> Requirement already satisfied: six in ./opt/anaconda3/lib/python3.7/site-packages (from absl-py->trimmed-match==1.0.0) (1.15.0)
> 
> Requirement already satisfied: pillow>=6.2.0 in ./opt/anaconda3/lib/python3.7/site-packages (from matplotlib->trimmed-match==1.0.0) (6.2.0)
> 
> Requirement already satisfied: cycler>=0.10 in ./opt/anaconda3/lib/python3.7/site-packages (from matplotlib->trimmed-match==1.0.0) (0.10.0)
> 
> Requirement already satisfied: python-dateutil>=2.1 in ./opt/anaconda3/lib/python3.7/site-packages (from matplotlib->trimmed-match==1.0.0) (2.8.0)
> 
> Requirement already satisfied: kiwisolver>=1.0.1 in ./opt/anaconda3/lib/python3.7/site-packages (from matplotlib->trimmed-match==1.0.0) (1.1.0)
> 
> Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in ./opt/anaconda3/lib/python3.7/site-packages (from matplotlib->trimmed-match==1.0.0) (2.4.2)
> 
> Requirement already satisfied: setuptools in ./opt/anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->trimmed-match==1.0.0) (51.3.3)
> 
> Requirement already satisfied: pytz>=2017.2 in ./opt/anaconda3/lib/python3.7/site-packages (from pandas->trimmed-match==1.0.0) (2019.3)
> 
> Building wheels for collected packages: trimmed-match
> 
>   Building wheel for trimmed-match (setup.py) ... error
> 
>   ERROR: Command errored out with exit status 1:
> 
>    command: /Users/username/opt/anaconda3/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4l/g4glrsp94337rjpdfdjhq9gw0000gn/T/pip-req-build-y26s5sr9/setup.py'"'"'; __file__='"'"'/private/var/folders/4l/g4glrsp94337rjpdfdjhq9gw0000gn/T/pip-req-build-y26s5sr9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/4l/g4glrsp94337rjpdfdjhq9gw0000gn/T/pip-wheel-ewzag689
> 
>        cwd: /private/var/folders/4l/g4glrsp94337rjpdfdjhq9gw0000gn/T/pip-req-build-y26s5sr9/
> 
>   Complete output (5 lines):
> 
>   running bdist_wheel
> 
>   running build
> 
>   running build_py
> 
>   creating build
> 
>   error: could not create 'build': File exists
> 
>   ----------------------------------------
> 
>   ERROR: Failed building wheel for trimmed-match
> 
>   Running setup.py clean for trimmed-match
> 
> Failed to build trimmed-match
> 
> Installing collected packages: trimmed-match
> 
>     Running setup.py install for trimmed-match ... error
> 
>     ERROR: Command errored out with exit status 1:
> 
>      command: /Users/username/opt/anaconda3/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4l/g4glrsp94337rjpdfdjhq9gw0000gn/T/pip-req-build-y26s5sr9/setup.py'"'"'; __file__='"'"'/private/var/folders/4l/g4glrsp94337rjpdfdjhq9gw0000gn/T/pip-req-build-y26s5sr9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/4l/g4glrsp94337rjpdfdjhq9gw0000gn/T/pip-record-u_3c5b_3/install-record.txt --single-version-externally-managed --compile --install-headers /Users/username/opt/anaconda3/include/python3.7m/trimmed-match
> 
>          cwd: /private/var/folders/4l/g4glrsp94337rjpdfdjhq9gw0000gn/T/pip-req-build-y26s5sr9/
> 
>     Complete output (5 lines):
> 
>     running install
> 
>     running build
> 
>     running build_py
> 
>     creating build
> 
>     error: could not create 'build': File exists
> 
>     ----------------------------------------
> 
> ERROR: Command errored out with exit status 1: /Users/username/opt/anaconda3/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4l/g4glrsp94337rjpdfdjhq9gw0000gn/T/pip-req-build-y26s5sr9/setup.py'"'"'; __file__='"'"'/private/var/folders/4l/g4glrsp94337rjpdfdjhq9gw0000gn/T/pip-req-build-y26s5sr9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/4l/g4glrsp94337rjpdfdjhq9gw0000gn/T/pip-record-u_3c5b_3/install-record.txt --single-version-externally-managed --compile --install-headers /Users/username/opt/anaconda3/include/python3.7m/trimmed-match Check the logs for full command output.
> 

Thank you.

**Comment by marcolongfils** [comment]
Hi Wanyi,

We currently support only local installation of the library in Linux (not on MacOs). In the meantime, you can use the Trimmed Match library in a Jupyter notebook, e.g. through [Colaboratory](https://colab.sandbox.google.com/notebooks/intro.ipynb), where you can install the library in the runtime (either locally or in the cloud) using

```
BAZEL_VERSION = '3.0.0'
!wget https://github.com/bazelbuild/bazel/releases/download/{BAZEL_VERSION}/bazel-{BAZEL_VERSION}-installer-linux-x86_64.sh
!chmod +x bazel-{BAZEL_VERSION}-installer-linux-x86_64.sh
!./bazel-{BAZEL_VERSION}-installer-linux-x86_64.sh
!sudo apt-get install python3-dev python3-setuptools git
!git clone https://github.com/google/trimmed_match
!python3 -m pip install ./trimmed_match
```

and then you can import as always, e.g.

`from trimmed_match.post_analysis import trimmed_match_post_analysis`

You can have a look at the example notebooks in the subfolder "notebook" for an way to use the library to design and analyse a geo experiment.

I'm closing the issue for now, but let me know if you have further problems.

Regards,
Marco

**Comment by adiellm** [comment]
I'm interested in using this on mac OS as well. Could we very useful, Thanks!

**Comment by marcolongfils** [comment]
Hi, 

Thanks for the interest in the Trimmed Match library. Currently, we don't have any plans to support installation on either Windows or MacOS in the near future. I think you could try using a virtual machine with Linux on your Mac or follow the instructions in my above comment.
