### ISSUE TITLE
KeyError when uploading Data for Design spreadsheet

### ISSUE THREAD

**Issue by braggbear** [google/trimmed_match#2]
Hello.

I was able to get the upload to work when I used the sample spreadsheet but when I use my own spreadsheet I get the following error. Do you know why I am getting it?  Thanks.

KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2897             try:
-> 2898                 return self._engine.get_loc(casted_key)
   2899             except KeyError as err:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'response'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
2 frames
/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2898                 return self._engine.get_loc(casted_key)
   2899             except KeyError as err:
-> 2900                 raise KeyError(key) from err
   2901 
   2902         if tolerance is not None:

KeyError: 'response'

**Comment by marcolongfils** [comment]
Hello,

From the error log it seems as your spreadsheet does not have a column called "response". The spreadsheet in input must have the following mandatory columns: "date", "geo" (GMA/DMA/dGMA depending on the country), "response" (the main metric of which you want to measure incrementality, e.g. sales or transactions), and "cost" (the ad spend in a campaign/account). The names of the columns in the spreadsheet must exactly be date, geo, response, cost if you want to use the colab as is. For more information about the colab and the requirements, take a look at the [guide].(https://github.com/google/trimmed_match/blob/master/trimmed_match/g3doc/Trimmed_Match_design_colab_guide.md)

If you still have problems, could you please share a minimum spreadsheet that raises the error?

Thanks,
Marco

**Comment by marcolongfils** [comment]
Closing the issue for the moment after offline discussion with @braggbear as the error was resolved/does not persist after some formatting of the input data and a [bug fix](https://github.com/google/trimmed_match/commit/e8973839881a17eb3c3a4f266dda37dea7b8bd5a)

Feel free to reopen if the issue persists.
